name: GHGDrugs
main: nl.gewoonhdgaming.drugs.Main
version: 1.0
author: [WTGConner]
website: www.gewoonhdgaming.nl
commands:
   coke:
      description: Gebruik dit om cocaïne te krijgen!
      aliases: [coke]